sudo: required
language: lisp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cgroup-bin mercurial g++ make python flex bison g++-multilib

install:
  - make

script:
  - make test
