sudo: required
language: lisp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mercurial g++ make python flex bison g++-multilib
  - which cgexec || sudo apt-get install -y cgroup-bin

install:
  - make

script:
  - make test
